### ISSUE TITLE
How to send 'myproto' message ?

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mvijayasekhar/Wireshark_Dissectors#1]
Hi,

In your example, you have captured myproto message. But, how have you sent that message ?
Using socket application?

Regards,
Mehul

**Comment by mvijayasekhar** [comment]
Hi Mehul,

Yeah using UDP socket I sent the message.

Regards,
Vijaya Sekhar M

**Comment by mehul-m-prajapati** [comment]
Hi Vijay,

May you share the raw message logs which you have sent via UDP socket ?

Regards,
Mehul
